import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ButterflyIcon } from "./icons/butterfly";
export function Navigation() {
    const scrollToSection = (sectionId) => {
        const element = document.getElementById(sectionId);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth' });
        }
    };
    return (_jsx("nav", { className: "fixed top-0 w-full bg-white/95 backdrop-blur-sm border-b border-gray-100 z-50", children: _jsx("div", { className: "max-w-6xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(ButterflyIcon, { className: "text-orange-500 w-6 h-6 mr-2" }), _jsx("span", { className: "font-semibold text-lg text-gray-900", children: "Merziyah's Digital Home" })] }), _jsxs("div", { className: "hidden md:flex space-x-8", children: [_jsx("button", { onClick: () => scrollToSection('about'), className: "text-gray-600 hover:text-orange-500 transition-colors duration-200", children: "About" }), _jsx("button", { onClick: () => scrollToSection('experience'), className: "text-gray-600 hover:text-orange-500 transition-colors duration-200", children: "Experience" }), _jsx("button", { onClick: () => scrollToSection('case-studies'), className: "text-gray-600 hover:text-orange-500 transition-colors duration-200", children: "Case Studies" }), _jsx("button", { onClick: () => scrollToSection('writing'), className: "text-gray-600 hover:text-orange-500 transition-colors duration-200", children: "Writing" }), _jsx("button", { onClick: () => scrollToSection('personal'), className: "text-gray-600 hover:text-orange-500 transition-colors duration-200", children: "Personal" }), _jsx("button", { onClick: () => scrollToSection('contact'), className: "text-gray-600 hover:text-orange-500 transition-colors duration-200", children: "Contact" }), _jsx("a", { href: "/Merziyah_Poonawala_Resume.pdf", download: "Merziyah_Poonawala_Resume.pdf", className: "text-gray-600 hover:text-orange-500 transition-colors", children: "Resume" })] }), _jsx("button", { className: "md:hidden text-gray-600", children: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M4 6h16M4 12h16M4 18h16" }) }) })] }) }) }));
}
